[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'readonly', 'filename', 'modified' ],
  \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
  \ },
  \ }
'''


# ========== Auto completion ==========
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_add = '''
  set completeopt=menuone,noselect
  call ddc#custom#patch_global(#{
    \ ui: 'native',
    \ sources: ['lsp', 'file', 'around'],
    \ sourceOptions: #{
    \   _: #{
    \     matchers: ['matcher_head'],
    \     sorters: ['sorter_rank'],
    \     minAutoCompleteLength: 1,
    \   },
    \   around: #{ mark: 'A' },
    \   lsp: #{
    \     mark: 'L',
    \     isVolatile: v:true,
    \     forceCompletionPattern: '\.\w*',
    \   },
    \   file: #{
    \     mark: 'F',
    \     isVolatile: v:true,
    \     forceCompletionPattern: '\S/\S*',
    \   },
    \ },
    \ sourceParams: #{
    \   file: #{ mode: 'posix' },
    \   lsp: #{ enableResolveItem: v:true },
    \ },
    \ })
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
